### ISSUE TITLE
[feature] Add cart quantity to Cart link text

### ISSUE THREAD

**Issue by CryptoGrampy** [moneropay/baskket#1]
Would love to see a (3) after the Cart link text in the header that displays the total number of items in the cart on page load (pulled from localstorage, etc), and updates when an item is added to the cart.

**Comment by sausagenoods** [comment]
That'd be indeed great! It currently has no indication that an item is added to the cart.

**Comment by sausagenoods** [comment]
[Current latest commit](https://github.com/moneropay/baskket/commit/4fb4ec2c6ad80233dcb790b8b71f7982e5b4c7b0) implements this feature. Thank you :)
